### ISSUE TITLE
Console windows do not stay on top of main frame

### ISSUE THREAD

**Issue by antipole2** [antipole2/JavaScript_pi#53]
When focus moves from console, consoles disappear  behind canvas.
This happens when a file dialogue is opened or with a click on the canvas.
In the Parking test script, after the first dialogue, all parked consoles disappear behind the main frame.

**Comment by Rasbats** [comment]
`m_Console( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT("JavaScript"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 844,2000 ), long style = wxCAPTION|wxCLOSE_BOX|wxDEFAULT_DIALOG_STYLE|wxMINIMIZE_BOX|wxRESIZE_BORDER|wxSTAY_ON_TOP);`

Added in _JavaScriptgui.h_. Not yet tested.

**Comment by antipole2** [comment]
Added through wxFormBuilder, which is more permanent than editing _JavaScriptgui.h_ but not sufficient.
Have asked in Zulip #Master - 5.8.0

**Comment by antipole2** [comment]
Under OCPN5.6.2/wx3.1.5 console windows move with the frame.
Under OCPN5.7/x3.2 the consoles are not attached to the frame - at lease under MacOS.

**Comment by antipole2** [comment]
Proper behaviour under wx3.2.
Changes made to v2.0.2 to accommodate this.
