### ISSUE TITLE
Tools dialogue not all screen resolution aware

### ISSUE THREAD

**Issue by antipole2** [antipole2/JavaScript_pi#62]
The Tools dialogue sizing and fields are wrong on Windows hi-res screens and probably on Linux too.
This does not affect MacOS, which deals with screen resolution within the OS.
See [screen-shots here](https://github.com/antipole2/JavaScript_pi/issues/60#issuecomment-1486054240).

Problem is that the windows are set up using wxFormBuilder and it does not apply adjustments to the various constants in the form  design.

Possible solution: may have to be done by fixing up the attributes at runtime - ugh!

**Comment by antipole2** [comment]
Rick adds

Not all text shows when resized.
Make window bigger?  Attached to bottom and side resize?

![JS2-14Park-Expanded](https://user-images.githubusercontent.com/2363959/229145136-274bc83f-0145-4fc7-b7e6-f85060795327.png)

**Comment by rgleason** [comment]
Tony, I can manage with the plugin, if specific changes after wxFrmbuilder is the only way to fix it.
Maybe we let this sit until we learn more?
I don't believe anyone has had to make changes for these kinds of reasons after using wxFormBuilder, so maybe there is another way?

**Comment by antipole2** [comment]
Rick... please test build f8515c4 focusing on the Consoles tab only.
Have not addressed other tabs until I know how to fix, as tested on Consoles tab.

**Comment by rgleason** [comment]
Using 2.1 msvc-wx32  from here 49 minutes ago.
https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/

**Comment by rgleason** [comment]
Tony using [2.1.3+215.921a081](https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/?q=version%3A2.1.3%2B215.921a081)  I will add screenshots as they opened, you know what they are when showing everything.

Console, we need a little more width for the fields I think
![Screenshot (1391)](https://user-images.githubusercontent.com/2363959/229527365-e7bb7a65-e948-498e-abe5-3cb837a136c1.png)
Console
![Screenshot (1392)](https://user-images.githubusercontent.com/2363959/229527481-723e98e8-4693-4079-a848-610e1189a371.png)

Directory
![Screenshot (1393)](https://user-images.githubusercontent.com/2363959/229530395-079f7cce-c721-4aa3-b094-4bf0d218d097.png)

NMEA
![Screenshot (1394)](https://user-images.githubusercontent.com/2363959/229527894-f6603bdb-f664-4c81-a1b3-7e8bdc78b1ab.png)

Message
![Screenshot (1396)](https://user-images.githubusercontent.com/2363959/229527971-557b39f5-f9fd-4e2e-8969-604f58bc4fd8.png)

Parking
![Screenshot (1397)](https://user-images.githubusercontent.com/2363959/229529702-33e902d8-169e-4278-b48c-7e137bd7942c.png)

Help 
![Screenshot (1398)](https://user-images.githubusercontent.com/2363959/229529911-bb67356f-ff92-46fc-82cc-058ce33e460f.png)

Diagnostics
![Screenshot (1400)](https://user-images.githubusercontent.com/2363959/229531154-4e1addc0-81c8-4239-b03a-a51aca8fc6ed.png)



This is what expanded looks like for:

NMEA
![Screenshot (1395)](https://user-images.githubusercontent.com/2363959/229530690-65d18836-4922-4356-aa5e-7a83f2868bc2.png)

Directory
![Screenshot (1395)](https://user-images.githubusercontent.com/2363959/229531684-ac3273d3-83c3-4c02-acae-c3b0f6093640.png)

Diagnostics
![Screenshot (1401)](https://user-images.githubusercontent.com/2363959/229531048-e1c5a760-f42d-4268-8994-bf596683ea71.png)

**Comment by antipole2** [comment]
New build 3rd April 17:40 UK time in alpha 7726527 is another attempt at the Tools - Console and Directory tabs only.
Do not waste time on the others.  I need to learn how to fix the issues first.
Screenshots of just these two tabs, please.

**Comment by antipole2** [comment]
Build cab6862 has further attempts to fix the Tools.
Screenshots please - only of Consoles and Directory.
Please without any resizing.
Or if you have to resize to show all, please send unresized and then make clear which have been resized.
Thank you!

**Comment by rgleason** [comment]
I find https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/   06030a and  cab6862 below that.
Which one?  cab6862 is older.

**Comment by antipole2** [comment]
Rick.. you can use the latest.  But looks like you already have for those two screenshots, so no need to repeat.
Looks like I have more work to do on that.

But I must get on with cruise preparation!

**Comment by rgleason** [comment]
Tony, you are a marvel. Get on with cruise prep!  (must get started on the boat, soon I hope)

**Comment by antipole2** [comment]
Rick...  have had a serious go at this.  Wrote a simulator so I could see the effect.
Please give build 02522a1 in my Alpha repo a go and let me have screenshots of each tab if not OK.
Very uncertain about the Help tab and the text folding so would like one of that anyway.

**Comment by rgleason** [comment]
Tony - much better!

Consoles - Open
![Screenshot (1424)](https://user-images.githubusercontent.com/2363959/231308811-c737ea89-149c-417d-8a16-324d8fe08a16.png)

Directory  - Open
![Screenshot (1426)](https://user-images.githubusercontent.com/2363959/231308864-6e110cee-5288-4010-af8d-3c28c47f498d.png)

NMEA  - Open
![Screenshot (1429)](https://user-images.githubusercontent.com/2363959/231309107-30693499-7f98-44fb-934c-b781433b2a1b.png)

Message  - Open
![Screenshot (1430)](https://user-images.githubusercontent.com/2363959/231309490-069ae9ab-1fde-4feb-beb8-53eb529f9f2f.png)

Parking  - Open
![Screenshot (1431)](https://user-images.githubusercontent.com/2363959/231309707-74529681-fe76-46f0-8a96-a853a475dbed.png)

Diagnostics  - Open
![Screenshot (1432)](https://user-images.githubusercontent.com/2363959/231309806-f87a8e23-d100-4812-a58a-4104dc6045c9.png)

RESIZED BELOW

Consoles - Entries
![Screenshot (1425)](https://user-images.githubusercontent.com/2363959/231310130-4d32b501-2dfd-4016-be0c-06f5ffa8b4cf.png)

Directory - Resized
![Screenshot (1427)](https://user-images.githubusercontent.com/2363959/231310595-d4a957c2-4457-484b-b309-8b55610c5c42.png)

NMEA - Resized
![Screenshot (1430)](https://user-images.githubusercontent.com/2363959/231310940-be738896-4f53-422c-a801-8e3a494e1a5d.png)

Diagnostics - Resized.
![Screenshot (1433)](https://user-images.githubusercontent.com/2363959/231311439-4cb53b14-a739-4758-a123-31b9f46b62bd.png)

**Comment by antipole2** [comment]
Rick... Getting there!
Build 7ca8f50 has some adjustments including for losing buttons on unresized windows.  Please try.
And please let me see what the Help page looks like.

I note on your screenshots that some of the parked consoles are too deep.  They show more than the top bar.  I think I have fixed that.  The ones shown may be left over from before that fix.  So please remove them or unpark and re-park them to check they are parked with only the top bar showing.

**Comment by antipole2** [comment]
Resolved in current version.
