### ISSUE TITLE
Funny characters in some Tools tabs

### ISSUE THREAD

**Issue by Rasbats** [antipole2/JavaScript_pi#63]
[https://github.com/antipole2/JavaScript_pi/issues/60](https://github.com/antipole2/JavaScript_pi/issues/60)

See screen shots from @rgleason.

**Comment by Rasbats** [comment]
These quotes have not been 'translated' for Windows:
e.g. “Latitude” (It won't allow me to copy the ones used in the code! Perhaps just use single quotes.

**Comment by antipole2** [comment]
They originate from with wxFormBuilder.  On close examination therein, it looks like they got in as 'smart quotes'.
I have replaced them with straight ones, I think.  We will; see in the next build.
I do not want to use single quotes as they illustrate a JSON message, which uses the quotation mark.

**Comment by antipole2** [comment]
Should be fixed in  [alpha build bb9e490](https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/?page=1) for the message tab.
No fix possible for the Diagnostics string - displaying these characters on Windows IS the problem!

**Comment by rgleason** [comment]
![JS2-1Console](https://user-images.githubusercontent.com/2363959/229112253-58de52d0-f737-471e-87d6-892e7aefde7f.png)


Tight fields for entry.  Requires resize to pull down to see last line.
![JS2-2Console](https://user-images.githubusercontent.com/2363959/229111127-ba64a48f-3edc-4037-826f-865b02708ac2.png)

Requires resize
![JS2-3Directory](https://user-images.githubusercontent.com/2363959/229111320-6c38b8d0-2912-4b92-be1b-de1c2bb45a9e.png)

Nmea  after a resize.  It is just a thin strip when first opened.
![JS2-4nmea](https://user-images.githubusercontent.com/2363959/229111376-81599c22-49d5-4aa4-b6e7-351991f74246.png)

How Message Opens.
![JS2-5Message](https://user-images.githubusercontent.com/2363959/229111424-f37d7400-f0b3-4130-b9e5-addf84fbe71c.png)

How parking opens
![JS2-6Parking](https://user-images.githubusercontent.com/2363959/229111475-838e2237-392b-41cb-a3eb-68ef23b8b5d2.png)

How Help opens.
![JS2-7Help](https://user-images.githubusercontent.com/2363959/229111514-4d06dfa6-681e-419d-a4c3-2ed71298f691.png)

How diagonstics opens.
![JS2-8Diagnostics](https://user-images.githubusercontent.com/2363959/229111562-2c3b1b52-726b-465d-9036-f84c7aa76486.png)

Diagnostics resized.
![JS2-9Diagnostics](https://user-images.githubusercontent.com/2363959/229111612-cae32dca-28b5-43b6-84cf-286db99389e6.png)

Shrink  Minimize
![JS2-10Shrunk](https://user-images.githubusercontent.com/2363959/229111756-4dd7d1c2-a6c3-4813-84e6-88e66789056f.png)

Expand
![JS2-11Expand](https://user-images.githubusercontent.com/2363959/229111808-3b41cd33-27ce-40a4-99db-abf0932ef393.png)

Load Script
![JS2-12LoadScript](https://user-images.githubusercontent.com/2363959/229111837-9c84ce43-f286-40d6-9609-a0275cd4dd52.png)

Favorites
![JS2-13Fav](https://user-images.githubusercontent.com/2363959/229111858-f5b354d9-a2f6-4cf3-915c-eb91fbb5f8fd.png)

Park expanded and resized.
![JS2-14Park-Expanded](https://user-images.githubusercontent.com/2363959/229111947-1f18c488-f999-43f3-87db-39616649a654.png)

Dump
![JS2-15Duimp](https://user-images.githubusercontent.com/2363959/229112019-f847a8d9-5ffa-4209-939f-ca3bc04fd5c2.png)

Run script register, fields are too small for entry.
![JS2-16Register](https://user-images.githubusercontent.com/2363959/229112083-8c2ea412-59c3-45e0-a6d6-1a7a7e138073.png)

Message result
![JS2-17Message](https://user-images.githubusercontent.com/2363959/229112123-99f22ffd-14fa-4836-8420-5cf080dc3470.png)



```
JavaScript plugin version 2.1
JavaScript patch 3
JavaScript tools window DPI scaling factor 2.500000
wxWidgets version 3.2.1.0 or 3201
OCPN API version 1.18
Duktape version 20700
Not using svg
pJavaScript_pi->m_pconfig			0x000134f290
pJavaScript_pi->m_parent_window		0x00039cfc40
favouriteFiles:
	C:\Users\fcgle\Downloads\dialogue_demo.js
	C:\Users\fcgle\Downloads\yet-another-demo.js
recentFiles:
	C:\Users\fcgle\Downloads\another-demo.js
	C:\Users\fcgle\Downloads\second-dialog-demo.js
pJavaScript_pi->mpFirstConsole	0x000a368818

----------Console three----------
Console name:		three
this:					0x000a368818
mpNextConsole:		0x0016102018
mStatus:				DONE 
mRunningMain:		false
m_time_to_allocate:	1000ms
m_timeout_check_counter:	1
mWaitingCached:		true
mWaiting:			false
mpMessageDialog:	nullptr
isBusy():				false
isWaiting():			false
auto_run:			false
position:				screen x:36 y:44	DIP x:14 y:18
Size():				x:241 y:88	DIP	x:96 y:35	MinSize() x:241 y:87
m_parked:			true position x:14 y:18
isParked():			true
Messages callback table
	WMM_VARIATION_BOAT_REQUEST		
m_timerActionBusy:	false
Timers callback table
	(empty)
Menus callback table
	(empty)
m_dialog:			None
m_alert:				None
m_NMEAmessageFunction:		
m_activeLegFunction:		
m_exitFunction:	
m_explicitResult:		true
m_result:				Registration was cancelled
mscriptToBeRun:	false
No brief
mConsoleRepliesAwaited	0
No Duktape context

----------Console seconname----------
Console name:		seconname
this:					0x0016102018
mpNextConsole:		nullptr
mStatus:				(no status)
mRunningMain:		false
m_time_to_allocate:	1000ms
m_timeout_check_counter:	0
mWaitingCached:		true
mWaiting:			false
mpMessageDialog:	nullptr
isBusy():				false
isWaiting():			false
auto_run:			false
position:				screen x:85 y:160	DIP x:34 y:64
Size():				x:1877 y:1588	DIP	x:751 y:635	MinSize() x:324 y:87
m_parked:			false position x:0 y:0
isParked():			false
Messages callback table
	WMM_VARIATION_BOAT_REQUEST		
m_timerActionBusy:	false
Timers callback table
	(empty)
Menus callback table
	(empty)
m_dialog:			None
m_alert:				None
m_NMEAmessageFunction:		
m_activeLegFunction:		
m_exitFunction:	
m_explicitResult:		false
m_result:				
mscriptToBeRun:	false
No brief
mConsoleRepliesAwaited	0
No Duktape context

----------------------------------------------------

pJavaScript_pi->mpBin		nullptr

End of dump
```

**Comment by rgleason** [comment]
Sorry used wrong issue.

**Comment by antipole2** [comment]
Deleted comments not relevant to this issue.
Issue resolved in current version.
