### ISSUE TITLE
Dialogue created by onDialogue not screen resolution aware

### ISSUE THREAD

**Issue by antipole2** [antipole2/JavaScript_pi#64]
The dialogue created probably has wrong sizing on Windows hi-res screens and likely on Linux too.
This does not affect MacOS, which deals with screen resolution within the OS.

Attached is a [test script (zipped)](https://github.com/antipole2/JavaScript_pi/files/11088413/dialogue_demo.js.zip).
It should look like [this (as on MacOS)](https://github.com/antipole2/JavaScript_pi/files/11088400/JS_dialogue.pdf).

@rgleason - please can you please try this and post a screenshot?

**Comment by antipole2** [comment]
First attempt to fix this in [alpha build bb9e490](https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/?page=1)

**Comment by rgleason** [comment]
Tony, using [alpha build bb9e490](https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/?page=1)

![JS2-16Register](https://user-images.githubusercontent.com/2363959/229141702-3ea2cf30-8e11-4874-ab58-c8db9307711b.png)

![JS2-17Message](https://user-images.githubusercontent.com/2363959/229141727-334c8aff-4cee-49f5-bee7-be13b1721b01.png)

**Comment by rgleason** [comment]
What branch is this Fixes in next build https://github.com/antipole2/JavaScript_pi/commit/f8515c42e1284bba8f42f26fc9fb0d52ab9a5c0a.
?

**Comment by antipole2** [comment]
> What branch is this Fixes in next build [f8515c4](https://github.com/antipole2/JavaScript_pi/commit/f8515c42e1284bba8f42f26fc9fb0d52ab9a5c0a).

v2.1

**Comment by rgleason** [comment]
Ok to make sure I am testing the right plugin tarball please advise which cloudsmith repos,  is it alpha?
https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/
That is what I have been using, the most recent version.

**Comment by antipole2** [comment]
Yes, alpha as per your link.

**Comment by rgleason** [comment]
Using https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/

![Screenshot (1384)](https://user-images.githubusercontent.com/2363959/229387599-4020fb39-3b0f-4571-ba01-0d00c805b2ff.png)


![Screenshot (1380)](https://user-images.githubusercontent.com/2363959/229387618-bedabe8c-6a72-49fa-bb73-a1e0ce91b006.png)

**Comment by antipole2** [comment]
New build in alpha repository fdc0127 attempts better fixes for JS dialogue.  Rick - please test.

**Comment by rgleason** [comment]
That one works!
![Screenshot (1386)](https://user-images.githubusercontent.com/2363959/229496516-e5fe953a-ced3-4765-9831-25a5d52e4449.png)
![Screenshot (1387)](https://user-images.githubusercontent.com/2363959/229496525-1f82e8d0-3495-4ef4-bd59-9032c0b34959.png)

**Comment by rgleason** [comment]
I think this can be closed now

**Comment by antipole2** [comment]
Rick... A big improvement - almost there.  The field heights were wrong.  New build 921a081 in the alpha repository.  
Please add an extra field for tick lists
After existing line
`{type:"spinner", label:"Draught (decimeters)", range:[10,30], value:20},`
add extra line
`{type:"tickList", label:"Down wind sails", value:["Spinnaker","Cruising 'chute", "Code 0"]},`
It should look like this.
![Dialogue](https://user-images.githubusercontent.com/11269557/229517997-7f35c979-9bb2-4daf-93c5-ec6361ea6eab.png)
Please check the dialogue again.

Also, please attend to [Tools Consoles tab]( https://github.com/antipole2/JavaScript_pi/issues/62#issuecomment-1492988995)
Thanks a lot.

**Comment by rgleason** [comment]
I tried adding the second line and the alert never showed.
I tried changing the added second line to 
{type:"tickList", label:"**Down wind sail**", value:["Spinnaker","Cruising 'chute", "Code 0"]},
and the alert did not work either. So I just removed it and saved the file and ran what I entered.  Don't understand why you ask me to add the second line as it is already there.

![Screenshot (1389)](https://user-images.githubusercontent.com/2363959/229524576-6317e03c-5e23-4a5e-bc6b-92c2128bb46b.png)

![Screenshot (1390)](https://user-images.githubusercontent.com/2363959/229524628-c8466927-d3a9-4930-9068-cfe0ee4f190f.png)

**Comment by antipole2** [comment]
Here's my script with the extra choice field repeating the ticklist.
[dialogue_demo.js.zip](https://github.com/antipole2/JavaScript_pi/files/11139072/dialogue_demo.js.zip)
And here is what it should look like

![withchoice](https://user-images.githubusercontent.com/11269557/229534632-650482a1-cfa6-4160-8cf5-0dc444f56acd.jpg)

**Comment by rgleason** [comment]
I guess you wanted spinner above, but here you are using choice?
Anyway I still seem to have the same error when I try to register, no yellow box filled appears. It is not really working for some reason. Loaded your file and these are the shots.


![Screenshot (1405)](https://user-images.githubusercontent.com/2363959/229562232-8b8445de-a157-40ac-9701-c219600bee46.png)

![Screenshot (1406)](https://user-images.githubusercontent.com/2363959/229562258-abb3609a-68f8-43ef-851f-bf61d68d1a4a.png)

**Comment by rgleason** [comment]
Yes please, I can't as I did not open it.

**Comment by antipole2** [comment]
Resolved!
