### ISSUE TITLE
Improve Parking so bottom window more useful

### ISSUE THREAD

**Issue by rgleason** [antipole2/JavaScript_pi#68]
Not all text shows when resized.
Make window bigger?  Attached to bottom and side resize?

![JS2-14Park-Expanded](https://user-images.githubusercontent.com/2363959/229145136-274bc83f-0145-4fc7-b7e6-f85060795327.png)

**Comment by antipole2** [comment]
Moved to [Tools dialogue issue](https://github.com/antipole2/JavaScript_pi/issues/62#issuecomment-1492248873) - its part of that one
