### ISSUE TITLE
Idea: When width is resized smaller  have   "Minimize, Tools, Help"  slide over to left?

### ISSUE THREAD

**Issue by rgleason** [antipole2/JavaScript_pi#69]
![Upper-right-1](https://user-images.githubusercontent.com/2363959/229157006-4c39871f-945e-4297-b569-abe001917c96.png)

![Resize-Width](https://user-images.githubusercontent.com/2363959/229157017-3ec2ba10-d795-4d47-ac79-280293868542.png)

**Comment by antipole2** [comment]
Impracticable - sorry.  How it is how wxWidgets works.
