### ISSUE TITLE
Canboatjs

### ISSUE THREAD

**Issue by rgleason** [antipole2/JavaScript_pi#72]
Tony, perhaps you know about this effort which may be of some interest?
https://github.com/canboat/canboatjs

**Comment by antipole2** [comment]
Thanks - yes I am aware of it.
 It is on my list to look into once I have established how to work OCPN input streams in a dynamic environment where everything has to be set up at script run time and not baked into plugin code as envisaged by developers.  It is proving a challenge :-#)

**Comment by rgleason** [comment]
Yes, understood. Closing
