### ISSUE TITLE
Windows download for v3.0 Build 1e Apr  1 2024 from catalogue has checksum error

### ISSUE THREAD

**Issue by antipole2** [antipole2/JavaScript_pi#90]
@bcn @seeUlater
[See discussion here](https://www.cruisersforum.com/forums/f134/vdr-plugin-59808-10.html#post3888299).

Don't understand how this got through the checks.  Have asked Dave's advice.

**Comment by bdbcat** [comment]
Usually this happens because the CI build process has been repeated, with no real code change.  I think...
Best solution:  Bump the version number, and resubmit the CI build

**Comment by Rasbats** [comment]
On Windows with OpenCPN 5.9.x I did not have a problem.

**Comment by antipole2** [comment]
v3.0.1 now in catalogue.
Please can SKS check if it installs on Windows this time?

**Comment by antipole2** [comment]
I hear that v3.0.1 can be installed through the catalogue on Windows.

**Comment by antipole2** [comment]
losing as issue resolved with new build
